### ISSUE TITLE
feat: dynamic connections at sidebar

### ISSUE THREAD

**Issue by DanielHe4rt** [basementdevs/scylla-studio#23]
We should start to look at the dynamic connections at the sidebar which brings the keyspace tables and other related items (soon).

![image](https://github.com/user-attachments/assets/86c10727-09f6-4c30-ad50-15be58974454)

Currently it's hardcoded to localhost:9042 but we can use a `Select` at this sidebar before rendering the Keyspaces like it was at v0.

![image](https://github.com/user-attachments/assets/058b8d1d-dd53-4a82-b726-306fe1b5213c)

**Comment by PedroFelli** [comment]
@DanielHe4rt  you can assign this to me ? 
![ezgif-5-623b969aa4](https://github.com/user-attachments/assets/780104d6-e4b1-4626-af31-7748e131cb5e)
