### ISSUE TITLE
refactor: migrate from react context to zustand for state management

### ISSUE THREAD

**Issue by Daniel-Boll** [basementdevs/scylla-studio#31]
The current implementation of the state management for `LayoutContext` in Scylla Studio is using React Context API. While this approach works for small-scale state management, it has limitations in terms of performance and scalability as the application grows. Zustand offers a simpler and more efficient state management solution that could address these limitations.

#### Problems with the Current Implementation

1. **Performance Issues**: With React Context, any change in the context triggers a re-render for all the components that consume the context. As more state variables are added to the context, this could lead to unnecessary re-renders, affecting the performance.
2. **Scalability Concerns**: As the application grows, managing complex states using React Context becomes cumbersome, especially with nested state updates.
3. **State Synchronization**: The current approach requires manual synchronization and updates for each state variable (e.g., `keyspaces`, `connections`). Zustand's approach to state management can simplify this by leveraging a more declarative state definition.
4. **Asynchronous Actions and Effects**: Handling asynchronous side effects like fetching data is more straightforward with Zustand's built-in support for middlewares and action management.

#### Proposed Solution

Migrate the current state management from React Context API to Zustand. Zustand provides a more optimized and flexible state management solution with a smaller learning curve compared to other state management libraries.

The migration involves:
- Replacing the existing `LayoutContext` and `useLayout` hooks with Zustand's state management.
- Simplifying state updates and side effects using Zustand's built-in support for actions.

#### Example of Zustand Implementation

Below is an example of how the state management could be implemented with Zustand.

```typescript
"use client";

import create from "zustand";
import { toast } from "sonner";
import type { ScyllaKeyspace } from "@lambda-group/scylladb";
import { queryKeyspaceAction } from "@scylla-studio/actions/query-keyspaces";
import { fetchConnections } from "@scylla-studio/app/(main)/connections/actions/connections";
import { KeyspaceDefinition } from "@scylla-studio/lib/cql-parser/keyspace-parser";
import type { Connection } from "@scylla-studio/lib/internal-db/connections";
import { useAction } from "next-safe-action/hooks";

interface LayoutState {
  keyspaces: Record<string, ScyllaKeyspace>;
  betterKeyspaces: Record<string, KeyspaceDefinition>;
  connections: Connection[];
  selectedConnection: Connection | undefined;
  setKeyspaces: (keyspaces: Record<string, ScyllaKeyspace>) => void;
  setBetterKeyspaces: (betterKeyspaces: Record<string, KeyspaceDefinition>) => void;
  setConnections: (connections: Connection[]) => void;
  setSelectedConnection: (connection: Connection | undefined) => void;
  fetchInitialConnections: () => Promise<void>;
  queryKeyspace: (connection: Connection) => Promise<void>;
}

export const useLayoutStore = create<LayoutState>((set, get) => ({
  keyspaces: {},
  betterKeyspaces: {},
  connections: [],
  selectedConnection: undefined,

  setKeyspaces: (keyspaces) => set({ keyspaces }),
  setBetterKeyspaces: (betterKeyspaces) => set({ betterKeyspaces }),
  setConnections: (connections) => set({ connections }),
  setSelectedConnection: (connection) => set({ selectedConnection: connection }),

  fetchInitialConnections: async () => {
    try {
      const initialConnections = await fetchConnections();
      set({ connections: initialConnections });
    } catch (error) {
      toast.error("Failed to fetch initial connections.");
    }
  },

  queryKeyspace: async (connection) => {
    const queryKeyspace = useAction(queryKeyspaceAction, {
      onExecute: () => {},
      onSuccess: ({ data }) => {
        if (data?.keyspaces) get().setKeyspaces(data.keyspaces);
        if (data?.betterKeyspaces) get().setBetterKeyspaces(data.betterKeyspaces);
      },
      onError: (error) => {
        console.error(error);
        toast.error("Failed to query keyspaces.");
        get().setSelectedConnection(undefined);
        get().setKeyspaces({});
      },
    });

    await queryKeyspace.execute({
      host: connection.host,
      port: connection.port,
      password: connection.password,
      username: connection.username,
    });
  },
}));

// Example usage in a component
import { useLayoutStore } from "./path-to-store";

export function LayoutProvider({ children }: { children: React.ReactNode }) {
  const {
    fetchInitialConnections,
    queryKeyspace,
    selectedConnection,
    setSelectedConnection,
  } = useLayoutStore();

  useEffect(() => {
    fetchInitialConnections();
  }, [fetchInitialConnections]);

  useEffect(() => {
    if (selectedConnection) {
      queryKeyspace(selectedConnection);
    }
  }, [queryKeyspace, selectedConnection]);

  return <>{children}</>;
}
```

#### Advantages of Using Zustand

1. **Improved Performance**: Zustand only re-renders components that consume the state variables being updated, avoiding unnecessary re-renders.
2. **Simpler State Management**: Zustand provides a simple and intuitive API for managing state and actions without the boilerplate associated with React Context.
3. **Easier to Handle Side Effects**: Zustand's support for asynchronous actions allows handling side effects directly within the store, simplifying state updates.
4. **Declarative State Updates**: Zustand encourages a more declarative way of managing state, reducing manual updates and synchronization of state variables.

#### Steps to Complete the Migration

1. **Create Zustand Store**: Implement a new store using Zustand that mirrors the state variables and actions from the existing `LayoutContext`.
2. **Replace `LayoutContext` and `useLayout`**: Update components to use the Zustand store instead of the `useContext` and `LayoutContext.Provider` pattern.
3. **Refactor State Updates**: Move state update logic, such as `fetchInitialConnections` and `queryKeyspace`, into the Zustand store.
4. **Testing and Validation**: Ensure that the new implementation works as expected, with proper testing for the state updates and side effects.

**Comment by void-hr** [comment]
@Daniel-Boll hello once again, I want to give it a try. I never worked with Zustand but  used rtk for state management.

**Comment by void-hr** [comment]
Using similar steps to run the app as before, but it is crashing. 

Steps that I followed 

1. git clone 
2. pnpm i (default branch)
3. pnpm dev

` ⨯ Error: Failed to load external module @lambda-group/scylladb: Error: Cannot find module '@lambda-group/scylladb-win32-x64-msvc'`

**Comment by Daniel-Boll** [comment]
Oh, no. You see, this is a problem with the NodeJS Scylla driver itself, it cannot run on Windows as of right now, you can try to run it on docker and develop with docker compose.

**Comment by void-hr** [comment]
@Daniel-Boll  can you guide me through this , getting this access error on docker compse

![Docker](https://github.com/user-attachments/assets/5f0d16ee-5ef9-4abb-82f0-d90d3729e29e)

**Comment by void-hr** [comment]
Yes sure, first try the one in readme run via docker and after that i tried `docker compose up`, I got this error via docker compose up

**Comment by void-hr** [comment]
> > @Daniel-Boll  can you guide me through this , getting this access error on docker compose
> > ![Docker](https://private-user-images.githubusercontent.com/89070559/375602984-5f0d16ee-5ef9-4abb-82f0-d90d3729e29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTMzNjQsIm5iZiI6MTcyODYxMzA2NCwicGF0aCI6Ii84OTA3MDU1OS8zNzU2MDI5ODQtNWYwZDE2ZWUtNWVmOS00YWJiLTgyZjAtZDkwZDM3MjllMjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyMTc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNzM3MGQ0ODA3YzY1YTg3YmUwNWUxZWYzYzg1NTcyOTc5ZjVhYWU4Y2I1ZjFjMjQ2ZDQ5MTIxNmY2N2VmZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1A7Yl_K4bZAVZXrrN_iaQiCNSv3YwOb2jdnZdd1_ve8)
> 
> Can you show me the command you ran please?

Yes sure, first try the one in readme run via docker and after that i tried `docker compose up`, I got this error via docker compose up

**Comment by Daniel-Boll** [comment]
Oh, yeah, we need to change the compose image from `basementdevs/scylla-studio` to `ghcr.io/basementdevs/scylla-studio:latest` try that please

**Comment by void-hr** [comment]
Yes it worked, but due to lack of resources I temporarily limit my cpu to 4 in compose yml, so seastar could not be initialized but ui is working fine, I hope I am good to work on my zustand migration

**Comment by Daniel-Boll** [comment]
> Yes it worked, but due to lack of resources I temporarily limit my cpu to 4 in compose yml.

Yeah, Ideally this should be some sort of enviroment variable that we will indicate the contributors to run with.

**Comment by void-hr** [comment]
Hey I nearly refactored code to migrate, can you help me with queryKeySpace part, like we can't use hook `useAction` in this case.

``` js
queryKeyspace: async (connection) => {
    const queryKeyspace = useAction(queryKeyspaceAction, {
      onExecute: () => {},
      onSuccess: ({ data }) => {
        if (data?.keyspaces) get().setKeyspaces(data.keyspaces);
        if (data?.betterKeyspaces) get().setBetterKeyspaces(data.betterKeyspaces);
      },
      onError: (error) => {
        console.error(error);
        toast.error("Failed to query keyspaces.");
        get().setSelectedConnection(undefined);
        get().setKeyspaces({});
      },
    });
   ```
  I tried to do this part the following way, 
 ``` js 
    queryKeyspace: (selectedConnection) => {
    const queryKeyspace = queryKeyspaceAction({
      host: selectedConnection.host,
      port: selectedConnection.port,
      password: selectedConnection.password,
      username: selectedConnection.username,
    });


    queryKeyspace
      .then(({ data }) => {
        if (data?.keyspaces) {
          set({ keyspaces: data.keyspaces });
        }
        if (data?.betterKeyspaces) {
          set({ betterKeyspaces: data.betterKeyspaces });
        }
      })
      .catch((error) => {
        console.log(error);
        toast.error("Failed to query keyspaces.");
        set({ selectedConnection: undefined, keyspaces: {} });
      });
  },
  ```

**Comment by DanielHe4rt** [comment]
Done at #38!

Thanks @void-hr <3
